## Reto 1 – Análisis de temperatura y humedad

**Objetivo:** Analizar la relación entre la temperatura, la humedad y la biomasa.

Carga el conjunto de datos y explora las variables relevantes.

In [2]:
import pandas as pd

df = pd.read_csv("../data/resultados_experimentos.csv")
df.head()

                    sitio  temperatura  humedad   luz  biomasa
0  Bosque Alto de Nocaima         23.8     82.2  1030    250.8
1      Humedal Facatativá         18.0     89.7   395    225.8
2       Río San Francisco         17.2     85.4   647    237.5
3       Ladera de La Vega         21.7     81.4   769    252.4
4   Zona Húmeda El Vergel         24.1     85.3  1333    302.7

## Exploración inicial
Describe las columnas y analiza los tipos de datos.

In [3]:
# Escribe tu código aquí para explorar el DataFrame
print(df.columns)

Index(['sitio', 'temperatura', 'humedad', 'luz', 'biomasa'], dtype='str')

## Desarrollo del reto
Aplica funciones y análisis según el objetivo. Usa `def` para definir tus funciones.

In [7]:
# Crea aquí tus funciones y análisis de cada reto (Resumen termico)
def resumen_termico(df):

    resumen = pd.DataFrame({
        "Promedio Temperatura": [df["temperatura"].mean()],
        "Máxima Temperatura": [df["temperatura"].max()],
        "Mínima Temperatura": [df["temperatura"].min()],
        "Promedio Humedad": [df["humedad"].mean()],
        "Máxima Humedad": [df["humedad"].max()],
        "Mínima Humedad": [df["humedad"].min()]
    })

    return resumen
resumen_termico(df)

,Promedio Temperatura,Máxima Temperatura,Mínima Temperatura,Promedio Humedad,Máxima Humedad,Mínima Humedad
0,20.695,27.7,14.8,78.09,93.0,63.2

## Crea aquí tus funciones y análisis de cada reto (clima, temperatura y humedad)
La función sirve para clasificar el tipo de clima según:

la temperatura (temp)
y la humedad (hum).

In [8]:
def clasificar_clima(temp, hum):

    if temp >= 20 and hum >= 60:
        return "húmedo templado"

    elif temp >= 20 and hum < 60:
        return "seco templado"

    elif temp < 20 and hum >= 60:
        return "húmedo frío"

    else:
        return "seco frío"
    df["clima"] = df.apply(
    lambda fila: clasificar_clima(fila["temperatura"], fila["humedad"]),
    axis=1
)

df.head()

                    sitio  temperatura  humedad   luz  biomasa
0  Bosque Alto de Nocaima         23.8     82.2  1030    250.8
1      Humedal Facatativá         18.0     89.7   395    225.8
2       Río San Francisco         17.2     85.4   647    237.5
3       Ladera de La Vega         21.7     81.4   769    252.4
4   Zona Húmeda El Vergel         24.1     85.3  1333    302.7

## Generar tabla de frecuencias
apply() recorre cada fila del DataFrame y ejecuta la función usando:

la temperatura de esa fila
y la humedad de esa fila.

In [9]:
df["clima"] = df.apply(
    lambda fila: clasificar_clima(fila["temperatura"], fila["humedad"]),
    axis=1
)

df.head()

,sitio,temperatura,humedad,luz,biomasa,clima
0,Bosque Alto de Nocaima,23.8,82.2,1030,250.8,húmedo templado
1,Humedal Facatativá,18.0,89.7,395,225.8,húmedo frío
2,Río San Francisco,17.2,85.4,647,237.5,húmedo frío
3,Ladera de La Vega,21.7,81.4,769,252.4,húmedo templado
4,Zona Húmeda El Vergel,24.1,85.3,1333,302.7,húmedo templado

## Tabla de frecuencia

In [10]:
tabla_frecuencias = df["clima"].value_counts()

print(tabla_frecuencias)

clima
húmedo templado    11
húmedo frío         9
Name: count, dtype: int64

In [11]:
# DataFrame final limpio
print(df)

                        sitio  temperatura  humedad   luz  biomasa  \
0      Bosque Alto de Nocaima         23.8     82.2  1030    250.8
1          Humedal Facatativá         18.0     89.7   395    225.8
2           Río San Francisco         17.2     85.4   647    237.5
3           Ladera de La Vega         21.7     81.4   769    252.4
4       Zona Húmeda El Vergel         24.1     85.3  1333    302.7
5              Río Subachoque         19.9     71.3   563     75.0
6            Humedal Mosquera         27.7     72.7   854    279.1
7                  Río Madrid         23.6     68.0  1482    123.1
8          Reserva San Miguel         20.7     70.3   899    108.3
9           Ladera de Sasaima         19.5     82.1  1016    221.7
10          Bosque de Guaduas         18.8     63.2   401     78.7
11             Humedal Cajicá         24.2     75.2  1283    315.6
12                Río Villeta         20.1     75.1  1004    238.2
13              Quebrada Cune         14.8     77.3   931    267.0
14            Bosque de Tenjo         19.6     74.9   678     54.8
15            Ladera de Tabio         24.3     70.9   630    228.3
16  Río Bogotá (tramo Sabana)         16.6     74.9   771    217.0
17              Humedal Gualí         16.5     91.3  1102     97.7
18         Reserva de Nocaima         21.4     93.0  1344     95.9
19    Bosque de San Francisco         21.4     77.6   888    258.7

              clima
0   húmedo templado
1       húmedo frío
2       húmedo frío
3   húmedo templado
4   húmedo templado
5       húmedo frío
6   húmedo templado
7   húmedo templado
8   húmedo templado
9       húmedo frío
10      húmedo frío
11  húmedo templado
12  húmedo templado
13      húmedo frío
14      húmedo frío
15  húmedo templado
16      húmedo frío
17      húmedo frío
18  húmedo templado
19  húmedo templado

## Interpretación de resultados
La mayoría de los sitios presentan climas húmedos, especialmente “húmedo templado” y “húmedo frío”. Se observó que los lugares con mayor humedad y temperaturas moderadas tienden a tener valores más altos de biomasa. En conclusión, la temperatura y la humedad influyen directamente en las condiciones ecológicas y en el crecimiento de la biomasa, asi se nota los cmabios.